package se.vgregion.core.infrastructure.persistence;

import java.io.Serializable;

import se.vgregion.core.domain.patterns.entity.Entity;
import se.vgregion.core.domain.patterns.repository.Repository;

/**
 * An extended repository interface with additional methods for find and remove {@link Entity entities} by its
 * database primary key.
 * 
 * @param <T>
 *            The Entity Type
 * @param <ID>
 *            The ID of the Entity
 * @param <PK>
 *            The type of the primary key
 * 
 * @author Anders Asplund - <a href="http://www.callistaenterprise.se">Callista Enterprise</a>
 */
public interface DatabaseRepository<T extends Entity<T, ID>, ID extends Serializable, PK extends Serializable>
        extends Repository<T, ID> {

    /**
     * Finds the instance of <code>T</code> identified by the database primary key. The primary key and the ID of
     * the entity is not necessarily the same. I.e the ID of a person could be it's social security number, while
     * the primary key is normally generated by the database.
     * 
     * @param pk
     *            The primary key
     * @return an object of <code>T</code>
     */
    T findByPrimaryKey(PK pk);

    /**
     * Remove entity by the database primary key. The primary key and the ID of the entity is not necessarily the
     * same. I.e the ID of a person could be it's social security number, while the primary key is normally
     * generated by the database.
     * 
     * @param pk
     *            The primary key
     * 
     */
    void removeByPrimaryKey(PK pk);
}
